import React from 'react';
import '../styles/Dashboard.scss';
import MainLayout from './layouts/MainLayout';

const Dashboard: React.FC = () => {
    return (
        <MainLayout>
            <div className="dashboard">
                <p>Dashboard</p>                
                <p>Dashboard</p>                
                <p>Dashboard</p>                
                <p>Dashboard</p>                
                <p>Dashboard</p>                
                <p>Dashboard</p>                
                <p>Dashboard</p>                
                <p>Dashboard</p>                
                <p>Dashboard</p>                
                <p>Dashboard</p>                
                <p>Dashboard</p>                
                <p>Dashboard</p>                
                <p>Dashboard</p>                
                <p>Dashboard</p>                
                <p>Dashboard</p>                
                <p>Dashboard</p>                
                <p>Dashboard</p>                
                <p>Dashboard</p>                
                <p>Dashboard</p>                
                <p>Dashboard</p>                
                <p>Dashboard</p>                
                <p>Dashboard</p>                
                <p>Dashboard</p>                
                <p>Dashboard</p>                
                <p>Dashboard</p>                
                <p>Dashboard</p>                
                <p>Dashboard</p>                
                <p>Dashboard</p>                
                <p>Dashboard</p>                
                <p>Dashboard</p>                
                <p>Dashboard</p>                
                <p>Dashboard</p>                
                <p>Dashboard</p>                
                <p>Dashboard</p>                
                <p>Dashboard</p>                
                <p>Dashboard</p>                
                <p>Dashboard</p>                
                <p>Dashboard</p>                
                <p>Dashboard</p>                
                <p>Dashboard</p>                
                <p>Dashboard</p>                
                <p>Dashboard</p>                
                <p>Dashboard</p>                
                <p>Dashboard</p>                
                <p>Dashboard</p>                
                <p>Dashboard</p>                
                <p>Dashboard</p>                
                <p>Dashboard</p>                
                <p>Dashboard</p>                
                <p>Dashboard</p>                
                <p>Dashboard</p>                
                <p>Dashboard</p>                
                <p>Dashboard</p>                
                <p>Dashboard</p>                
                <p>Dashboard</p>                
                <p>Dashboard</p>                
                <p>Dashboard</p>                
                <p>Dashboard</p>                
                <p>Dashboard</p>                
                <p>Dashboard</p>                
                <p>Dashboard</p>                
                <p>Dashboard</p>                
                <p>Dashboard</p>                
                <p>Dashboard</p>                
                <p>Dashboard</p>                
                <p>Dashboard</p>                
                <p>Dashboard</p>                
                <p>Dashboard</p>                
                <p>Dashboard</p>                
                <p>Dashboard</p>                
                <p>Dashboard</p>                
                <p>Dashboard</p>                
                <p>Dashboard</p>                
                <p>Dashboard</p>                
                <p>Dashboard</p>                
                <p>Dashboard</p>                
                <p>Dashboard</p>                
                <p>Dashboard</p>                
                <p>Dashboard</p>                
                <p>Dashboard</p>                
                <p>Dashboard</p>                
                <p>Dashboard</p>                
                <p>Dashboard</p>                
                <p>Dashboard</p>                
                <p>Dashboard</p>                
                <p>Dashboard</p>                
                <p>Dashboard</p>                
                <p>Dashboard</p>                
                <p>Dashboard</p>                
                <p>Dashboard</p>                
                <p>Dashboard</p>                
                <p>Dashboard</p>                
                <p>Dashboard</p>                
                <p>Dashboard</p>                
                <p>Dashboard</p>                
                <p>Dashboard</p>                
                <p>Dashboard</p>                
                <p>Dashboard</p>                
                <p>Dashboard</p>                
                <p>Dashboard</p>                
                <p>Dashboard</p>                
                <p>Dashboard</p>                
                <p>Dashboard</p>                
                <p>Dashboard</p>                
                <p>Dashboard</p>                
                <p>Dashboard</p>                
                <p>Dashboard</p>                
                <p>Dashboard</p>                
                <p>Dashboard</p>                
                <p>Dashboard</p>                
                <p>Dashboard</p>                
                <p>Dashboard</p>                
                <p>Dashboard</p>                
                <p>Dashboard</p>                
                <p>Dashboard</p>                
                <p>Dashboard</p>                
                <p>Dashboard</p>                
                <p>Dashboard</p>                
                <p>Dashboard</p>                
                <p>Dashboard</p>                
                <p>Dashboard</p>                
                <p>Dashboard</p>                
                <p>Dashboard</p>                
                <p>Dashboard</p>                
                <p>Dashboard</p>                
                <p>Dashboard</p>                
                <p>Dashboard</p>                
                <p>Dashboard</p>                
                <p>Dashboard</p>                
                <p>Dashboard</p>                
                <p>Dashboard</p>                
                <p>Dashboard</p>                
                <p>Dashboard</p>                
            </div>
        </MainLayout>
    );
};

export default Dashboard; 